[package]
name = "linux_project"
version = "0.1.0"
authors = ["aaryaac7@gmail.com"]
edition = "2023"

[dependencies]
actix-web = "3.3.2"

[dev-dependencies]
tokio = "1.0.0"

[build]
target = "x86_64-unknown-linux-musl"
