[package]
name = "my_project"
version = "0.1.0"
authors = ["Your Name <your@email.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"

[dev-dependencies]
tokio = "1.0.0"

[build]
target = "x86_64-unknown-linux-musl"
